# Input: teclado, mouse, touchpad, gestos
# Wiki: https://wiki.hypr.land/Configuring/Variables/#input

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

# Exemplo per-device (descomente e ajuste o nome com hyprctl devices)
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }
